joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

# Joint Trajectory Controller
grip_position:
    type: "position_controllers/JointTrajectoryController"
    joints: 
        - actuator_joint_1
        - actuator_joint_2
        - actuator_joint_3

    gains:
        actuator_joint_1: {p: 0, d: 0, i: 0}
        actuator_joint_2: {p: 0, d: 0, i: 0}
        actuator_joint_3: {p: 0, d: 0, i: 0}

    constraints:
        goal_time: 0.5
        actuator_1:
            trajectory: 0.5
            goal: 0.02
        actuator_2:
            trajectory: 0.5
            goal: 0.02
        actuator_3:
            trajectory: 0.5
            goal: 0.02

# Same gains as above
#gazebo_ros_control/pid_gains:
#    actuator_joint_1: {p: 0, d: 0, i: 0}
#    actuator_joint_2: {p: 0, d: 0, i: 0}
#    actuator_joint_3: {p: 0, d: 0, i: 0}