controller_list:
    - name: "/right/gripper/grip_position"
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
          - actuator_joint_1
          - actuator_joint_2
          - actuator_joint_3